### ISSUE TITLE
CMake files are incomplete?

### ISSUE THREAD

**Issue by flibitijibibo** [TwoTribesGames/ttengine#1]
Hey there!

I just cloned the source and took a look at the project files, and noticed that there are a few CMakeLists.txt files as well as some Makefile rules in the Linux folder. It looks like there are some things that may have been missed in the GPL release:

- Possibly a root CMakeLists.txt that groups `engine` and `game` together?
- Non-NDA contents of the `ttdev` folder
- A separate `tools/shared/` folder?

Aside from that it seems like the source itself is complete, but that's at a quick glance. In particular I'm interested in seeing if I can make [FAudio](https://github.com/FNA-XNA/FAudio) work with the Windows XACT data, to make it so non-Windows targets can share the same audio files without a conversion process.

In any case, thanks for releasing this code, it's very interesting to read through!

**Comment by MarByteBeep** [comment]
The Linux version was ported by an external coder. I've contacted him to see if he can shed some light on this issue.

**Comment by urkle** [comment]
@flibitijibibo hey Ethan!  Once Maartin gives me access I'll merge in any outstanding local changes from my last porting work and get the CMake scripts fixed up. (which I believe last I checked they worked for Win, Mac, and Linux)

**Comment by flibitijibibo** [comment]
Sounds good! Also, good to see you again :)

**Comment by MarByteBeep** [comment]
@urkle I just added you. Thanks a lot for handling this!!!

**Comment by urkle** [comment]
@flibitijibibo can you check out PR #2 

I made sure it "compiled" on macOS (via CLion using Xcode 12.4 compiler/sdk)

It should compile on linux as well (but I have not tested).. can you test it?  It should be as simple as doing

```bash
mkdir cmake-build-debug
cd cmake-build-debug
cmake -G Ninja .. -DCMAKE_BUILD_TYPE=Debug
cmake --build .
```

Let me know if it works or not.. If it's all good I'll merge this in.. and if you want to open a PR to make adjustments to the README I can review them.

**Comment by flibitijibibo** [comment]
Expect to hear from me on the 26th when I'll have access to the CentOS builder! At a glance this looks right to me; I think the root CMakeLists was the missing piece but ttdev may still need something important.

**Comment by xard-dev** [comment]
Hello,

I tried the debug build on Ubuntu 20.04 and after installing "ninja-build" the cmake configuration phase works.

However unfortunately the build process itself fails to following error messages:
```
./src/engine/shared/src/tt/compression/png.cpp:16:19: error: expected initializer before ‘pngReadData’
   16 | void      __cdecl pngReadData    (png_structp p_pngPtr, png_bytep p_targetData, png_size_t p_requestedLength);
      |                   ^~~~~~~~~~~
../src/engine/shared/src/tt/compression/png.cpp:17:19: error: expected initializer before ‘pngWriteData’
   17 | void      __cdecl pngWriteData   (png_structp p_pngPtr, png_bytep p_dataToWrite, png_size_t p_dataLength);
      |                   ^~~~~~~~~~~~
../src/engine/shared/src/tt/compression/png.cpp:18:19: error: expected initializer before ‘pngMalloc’
   18 | png_voidp __cdecl pngMalloc      (png_structp p_pngPtr, png_size_t p_size);
      |                   ^~~~~~~~~
../src/engine/shared/src/tt/compression/png.cpp:19:19: error: expected initializer before ‘pngFree’
   19 | void      __cdecl pngFree        (png_structp p_pngPtr, png_voidp p_ptr);
      |                   ^~~~~~~
../src/engine/shared/src/tt/compression/png.cpp:20:19: error: expected initializer before ‘pngReadError’
   20 | void      __cdecl pngReadError   (png_structp p_pngPtr, png_const_charp p_errorMessage);
      |                   ^~~~~~~~~~~~
../src/engine/shared/src/tt/compression/png.cpp:21:19: error: expected initializer before ‘pngReadWarning’
   21 | void      __cdecl pngReadWarning (png_structp p_pngPtr, png_const_charp p_errorMessage);
      |                   ^~~~~~~~~~~~~~
../src/engine/shared/src/tt/compression/png.cpp:22:19: error: expected initializer before ‘pngWriteError’
   22 | void      __cdecl pngWriteError  (png_structp p_pngPtr, png_const_charp p_errorMessage);
      |                   ^~~~~~~~~~~~~
../src/engine/shared/src/tt/compression/png.cpp:23:19: error: expected initializer before ‘pngWriteWarning’
   23 | void      __cdecl pngWriteWarning(png_structp p_pngPtr, png_const_charp p_errorMessage);
      |                   ^~~~~~~~~~~~~~~
```

[ttengine_cmake.log](https://github.com/TwoTribesGames/ttengine/files/7777351/ttengine_cmake.log)
[ttengine_build_error.log](https://github.com/TwoTribesGames/ttengine/files/7777352/ttengine_build_error.log)
